name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 480

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME for Buildozer
        run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ccache git zip unzip autoconf automake libtool pkg-config \
            python3-pip python3-dev zlib1g-dev libncurses5-dev libtinfo6 libffi-dev libssl-dev

      - name: Install Python packages (buildozer + cython)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user buildozer cython
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Show environment (debug)
        run: |
          python3 --version
          pip3 --version
          java -version
          echo $JAVA_HOME
          which buildozer || true
          ls -la

      - name: Build debug APK
        run: |
          ls -la
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
